# Generated by Django 3.1.4 on 2020-12-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livrusp', '0005_cad_compra_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cad_compra',
            name='usuario',
        ),
    ]
